heat_template_version: rocky

description: Static WordPress application

resources:

  dbvol:
    type: OS::Cinder::Volume
    properties:
      name: dbvol
      size: 1

  dbserver:
    type: OS::Nova::Server
    properties:
      image: fedora
      flavor: wpsmall
      networks: [network: "backend"]
      key_name: key1
      user_data_format: RAW
      user_data: 
        get_file: /home/nobleprog/openstack-bootcamp/module09/setup-wpdb.sh
      metadata:
        db_name: wordpress
        db_user: wpuser
        db_password: pw
      block_device_mapping: [ { device_name: "vdb", volume_id: { get_resource: dbvol } } ] 

