
heat_template_version: rocky

description: Static WordPress application with webserver and Floating IP

resources:

  dbvol:
    type: OS::Cinder::Volume
    properties:
      name: dbvol
      size: 1

# Most properties of dbserver should be self-explanatory.
# The metadata property corresponds to the --property option of
# openstack server create.
# User data format must be set to RAW, otherwise HEAT_CFNTOOLS is assumed.
# The networks property is a list of networks.
# block_device_mapping is a list of mappings. Each mapping is a set. 
# The volume ID is obtained from the dbvol resource above.

  dbserver:
    type: OS::Nova::Server
    properties:
      image: dbimage
      flavor: wpsmall
      networks: [network: "backend"]
      key_name: key1
      user_data_format: RAW
      user_data: 
        get_file: /home/nobleprog/openstack-bootcamp/module09/setup-wpdb.sh
      metadata:
        db_name: wordpress
        db_user: wpuser
        db_password: pw
      block_device_mapping: [ { device_name: "vdb", volume_id: { get_resource: dbvol } } ] 

# webserver is similar to dbserver. Image is fedora, different user_data,
# no block device mapping, and the ip_address metadata item is obtained from 
# the backend address of dbserver.

  webserver1:
    type: OS::Nova::Server
    properties:
      name: wp1
      image: fedora
      flavor: wpsmall
      networks: [port: { get_resource: webport }]
      key_name: key1
      user_data_format: RAW
      user_data: 
        get_file: /home/nobleprog/openstack-bootcamp/module09/setup-wpdb.sh
      metadata:
        db_name: wordpress
        db_user: wpuser
        db_password: pw
        db_ipaddress: { get_attr: [ dbserver, addresses, backend, 0, addr ] }

# The following resource adds wp1 to the loadbalancer pool.
# Again, get_attr is used to obtain its fixed IP address.

  lbmember-wp1:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      address: { get_attr: [ wp1, addresses, backend, 0, addr ] }
      admin_state_up: true
      pool: wppool
      protocol_port: 80
      subnet: timetravel-subnet
      weight: 1

  webserver2:
    type: OS::Nova::Server
    properties:
      name: wp2
      image: fedora
      flavor: wpsmall
      networks: [port: { get_resource: webport }]
      key_name: key1
      user_data_format: RAW
      user_data: 
        get_file: /home/nobleprog/openstack-bootcamp/module09/setup-wpdb.sh
      metadata:
        db_name: wordpress
        db_user: wpuser
        db_password: pw
        db_ipaddress: { get_attr: [ dbserver, addresses, backend, 0, addr ] }

  lbmember-wp2:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      address: { get_attr: [ wp2, addresses, backend, 0, addr ] }
      admin_state_up: true
      pool: wppool
      protocol_port: 80
      subnet: timetravel-subnet
      weight: 1
