
heat_template_version: rocky

description: Static WordPress application with webserver and Floating IP

resources:

  dbvol:
    type: OS::Cinder::Volume
    properties:
      name: dbvol
      size: 1

# Most properties of dbserver should be self-explanatory.
# The metadata property corresponds to the --property option of
# openstack server create.
# User data format must be set to RAW, otherwise HEAT_CFNTOOLS is assumed.
# The networks property is a list of networks.
# block_device_mapping is a list of mappings. Each mapping is a set. 
# The volume ID is obtained from the dbvol resource above.

  dbserver:
    type: OS::Nova::Server
    properties:
      image: fedora
      flavor: wpsmall
      networks: [network: "backend"]
      key_name: key1
      user_data_format: RAW
      user_data: 
        get_file: /home/nobleprog/openstack-bootcamp/module09/setup-wpdb.sh
      metadata:
        db_name: wordpress
        db_user: wpuser
        db_password: pw
      block_device_mapping: [ { device_name: "vdb", volume_id: { get_resource: dbvol } } ] 

# webserver is similar to dbserver. Image is fedora, different user_data,
# no block device mapping, and the ip_address metadata item is obtained from 
# the backend address of dbserver.

  webport:
    type: OS::Neutron::Port
    properties:
      name: webport
      network: "timetravel-net"
      security_groups: [default, web]
  
  webfip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public1
      port_id: { get_resource: webport }

  webserver1:
    type: OS::Nova::Server
    properties:
      name: wp1
      image: fedora
      flavor: wpsmall
      networks: [port: { get_resource: webport }]
      key_name: key1
      user_data_format: RAW
      user_data: 
        get_file: /home/nobleprog/openstack-bootcamp/module09/setup-wp.sh
      metadata:
        db_name: wordpress
        db_user: wpuser
        db_password: pw
        db_ipaddress: { get_attr: [ dbserver, addresses, backend, 0, addr ] }

